name = "lustre_browser_extension"
version = "1.0.0"
target = "javascript"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "username", repo = "project" }
# links = [{ title = "Website", href = "https://gleam.run" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/. 

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
lustre = ">= 4.5.1 and < 5.0.0"
plinth = ">= 0.5.0 and < 1.0.0"
gleam_json = ">= 2.0.0 and < 3.0.0"
tom = ">= 1.1.0 and < 2.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"
dot_env = ">= 1.2.0 and < 2.0.0"
gleam_otp = ">= 0.16.0 and < 1.0.0"
gleam_javascript = ">= 0.13.0 and < 1.0.0"
ref = ">= 0.3.3 and < 1.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
lustre_dev_tools = ">= 1.2.1 and < 2.0.0"
glailglind = ">= 1.1.2 and < 2.0.0"
lucide_lustre = ">= 2.0.0 and < 3.0.0"

[tailwind]
version = "3.4.1" # optional
args = [
    "--config=tailwind.config.js",
    "--input=./src/styles/app.css",
    "--output=./extension/priv/styles/app.css"
]

[lucide_lustre]
output_module = "components/lucide_icons"
